# Generated by Django 4.0.6 on 2022-08-07 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='timestamp',
            new_name='timeStamp',
        ),
    ]
